site_name: iclr
site_description: ...
site_author: moskomule
site_url: https://moskomule.github.io/iclr
repo_name: moskomule/iclr
repo_url: https://github.com/moskomule/iclr
edit_uri: blob/main/docs

theme:
  name: material

  features:
    - content.code.annotate

markdown_extensions:
  # mathjax
  - pymdownx.arithmatex:
      generic: true

  # syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'   